<!DOCTYPE HTML>
<html lang="en">
<head>
	<title>Blog dbz</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">


	<!-- Font -->

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">


	<!-- Stylesheets -->

	<link href="common-css/bootstrap.css" rel="stylesheet">

	<link href="common-css/ionicons.css" rel="stylesheet">


	<link href="category-sidebar/css/styles.css" rel="stylesheet">

	<link href="category-sidebar/css/responsive.css" rel="stylesheet">

</head>
<body >

	<header>
		<div class="">

			<a href="#" class="logo"><img src="images/dbz.png" alt="Logo Image"></a>

			<div class="menu-nav-icon" data-nav-menu="#main-menu"><i class="ion-navicon"></i></div>
			<ul class="main-menu " id="main-menu">
				<li><a href="index.php">Home</a></li>
				<li class="survol"><a href="#">Categories</a>
					<ul class="submenu">
					<?php foreach($category as $cat): ?>
						<li><a href="category.php?id=<?= $cat['Id'] ?>" class="liens-mm"><?= $cat['Name']?></a></li>
					<?php endforeach; ?>
								
					</ul>
				</li>
				<!--<li class="survol" style="display: <?php if(!isset($_SESSION['login'])){?> none; <?php } ?>"><a href="recap.php">Features</a>
					<ul class="submenu">					
						<li class="liens-mm"><a href="add_post.php" class="liens-mm">Nouvel Article</a></li>
						<li class="liens-mm"><a href="modifpost.php" class="liens-mm">Modifier un article</a></li>
						<li class="liens-mm"><a href="deletepost.php" class="liens-mm"></a>Supprimer un article</li>			
						<li class="liens-mm"><a href="recap.php" class="liens-mm">Tableau de bord</a></li>			
					</ul>
				</li>-->
				<li style="display: <?php if(isset($_SESSION['login'])){?> none; <?php } ?>"><a href="login.php">Connexion</a></li>
				<li style="display: <?php if(!isset($_SESSION['login'])){?> none; <?php } ?>"><a href="deconnexion-index.php">Déconnexion</a>
				</li>
				<li  class="bienvenue" style="display: <?php if(!isset($_SESSION['login'])){?> none; <?php } ?>;  color: green;" >Bienvenue <?= $_SESSION['login'] ?>
				</li>	
			</ul><!-- main-menu -->		
			<div class="src-area">
				<form>
					<button class="src-btn" type="submit"><i class="ion-ios-search-strong"></i></button>
					<input class="src-input" type="text" placeholder="Type of search">
				</form>
			</div>

		</div><!-- conatiner -->
	</header>

	<div class="slider display-table center-text">
		<h1 class="title display-table-cell"><b><?= 
		$namecat['Name']?></b></h1>
	</div><!-- slider -->
	
	<section class="blog-area section">
		<div class="container">

			<div class="row">

				<div class="col-lg-8 col-md-12">
					<div class="row">
					<?php foreach($post as $article): ?>
						<div class="col-md-6 col-sm-12">
							<div class="card h-100">
								<div class="single-post post-style-1 test">

									<div class="blog-image"><img src="<?= $article['Image']?>" alt="Blog Image"></div>

									<a class="avatar transitionpost" href="#"><img src="<?= $article['AuthorImage']?>" alt="Profile Image"></a>

									<div class="blog-info">

										<h4 class="title"><a href="#"><b><?= $article['Title']?></b></a></h4>

										<ul class="post-footer">
											<li><a href="#"><i class="ion-heart"></i>57</a></li>
											<li><a href="#"><i class="ion-chatbubble"></i>6</a></li>
											<li><a href="#"><i class="ion-eye"></i>138</a></li>
										</ul>

									</div><!-- blog-info -->
								</div><!-- single-post -->
							</div><!-- card -->
						</div><!-- col-md-6 col-sm-12 -->
						<?php endforeach; ?>			
					</div><!--
				 --><div class="col-lg-4 col-md-12 ">

					<div class="single-post info-area ">

						<div class="about-area">
							<h4 class="title"><b>ABOUT BONA</b></h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
								ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur
								Ut enim ad minim veniam</p>
						</div>

						<div class="subscribe-area">

							<h4 class="title"><b>SUBSCRIBE</b></h4>
							<div class="input-area">
								<form>
									<input class="email-input" type="text" placeholder="Enter your email">
									<button class="submit-btn" type="submit"><i class="ion-ios-email-outline"></i></button>
								</form>
							</div>

						</div><!-- subscribe-area -->

						<div class="tag-area">

							<h4 class="title"><b>TAG CLOUD</b></h4>
							<ul>
								<li><a href="#">Manual</a></li>
								<li><a href="#">Liberty</a></li>
								<li><a href="#">Recomendation</a></li>
								<li><a href="#">Interpritation</a></li>
								<li><a href="#">Manual</a></li>
								<li><a href="#">Liberty</a></li>
								<li><a href="#">Recomendation</a></li>
								<li><a href="#">Interpritation</a></li>
							</ul>

						</div><!-- subscribe-area -->

					</div><!-- info-area -->

				</div><!-- col-lg-4 col-md-12 -->

			</div><!-- row -->

		</div><!-- container -->
	</section><!-- section -->


	<footer>
		<div class="container">
			<div class="row">

				<div class="col-md-12">
					<div class="footer-section">

						<a class="logo" href="#"><img src="images/logo.png" alt="Logo Image"></a>
						<p class="copyright">Bona @ 2017. All rights reserved.</p>
						<p class="copyright">Designed by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
						<ul class="icons">
							<li><a href="#"><i class="ion-social-facebook-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-twitter-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-instagram-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-vimeo-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-pinterest-outline"></i></a></li>
						</ul>
					
					</div><!-- footer-section -->
				</div><!-- col-md-12 -->

			</div><!-- row -->
		</div><!-- container -->
	</footer>


	<!-- SCIPTS -->

	<script src="common-js/jquery-3.1.1.min.js"></script>

	<script src="common-js/tether.min.js"></script>

	<script src="common-js/bootstrap.js"></script>

	<script src="common-js/scripts.js"></script>

</body>
</html>
