<!DOCTYPE HTML>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<center>
			 <form id="login" action="login.php" method="POST" >			
			 		<label for="User">Nom d’utilisateur</label>
					<input name="User"  autofocus="autofocus" value="" placeholder="Entrez votre nom d’utilisateur." class="std_textbox" type="text"  tabindex="1" required>
					<label for="password">Mot de passe</label>
					<input name="Password" placeholder="Saisissez le mot de passe de votre compte." type="password" tabindex="2"  required>
					<button name="login" type="submit" id="login">Connexion</button>
			</form>
		</center>
	</body>
</html>