<form class="generic-form" action="modifpost.php" method="post">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
  

    <fieldset>
    <input type="hidden" name="Id" value="<?= $post['Id']?>">

        <legend><i class="fa fa-comment-o"></i>Article à modifier</legend>
        <label for="Title"> Titre :</label>
        
        <input type="text" name="Title" id="Title" value="<?= $post['Title']?>">

        <label for="categorie">Catégorie :</label>
        <select id="categorie " name="Category_Id">
            <?php foreach($Category as $category): ?>
                <option <?php if($post['Category_Id']==$category['Id']){echo "selected";} ?>        value="<?= $category['Id'] ?>"><?= $category['Name'] ?></option>
            <?php endforeach; ?>
        </select>
        <label for="Auteur ">Auteur :</label>
        <select name="Author_Id"> 
            <?php foreach($Author as $author): ?>
                <option <?php if($post['Author_Id']==$author['Id']){echo "selected";} ?> value="<?= $author['Id'] ?>"><?= $author['LastName'] ?></option>
            <?php endforeach; ?>
        </select>
        <ul>
           
            <li>
                <label for="Image">Image :</label>
                <input type="text" id="Image" value="<?= $post['Image']?>" name="Image">
            </li>
            <li>
                <label class="textarea" for="Contents">Article :</label>
                <textarea id="Contents" name="Contents" rows="5"><?= $post['Contents']?></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Modifier</button>
                <a class="button button-cancel" href="recap.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
