<!-- Page d'article de blog détaillé avec les commentaires -->
<h2><i class="fa fa-file-text-o"></i> Article</h2>

<!-- Article du blog -->
<section class="post">
    <h3><?= $post['Title'] ?></h3>
    <article><?= $post['Contents'] ?></article>
    <small>
        Rédigé par <?= ($post['FirstName']) ?> <?= $post['LastName'] ?>
        le <?= $post['CreationTimestamp'] ?>
    </small>
    <img src="<?= $post['Image'] ?>">
</section>

<hr>

<!-- Liste des commentaires de l'article du blog -->
<ul class="comment-list">
    <?php foreach($comments as $comment): ?>
        <li class="comment">
            <h4><i class="fa fa-comment"></i> Rédigé par <?= $comment['NickName'] ?></h4>
            <article><?= $comment['Contents'] ?></article>
        </li>
    <?php endforeach; ?>
</ul>

<hr>

<!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
<form class="generic-form" action="add_comment.php" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="nickName">Pseudo :</label>
                <input type="text" id="nickName" name="nickName">
            </li>
            <li>
                <label class="textarea" for="contents">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>